x-environment: &shared-variables
  PYTHONDONTWRITEBYTECODE: $PYTHONDONTWRITEBYTECODE
  CORS_ORIGIN: $CORS_ORIGIN
  FLASK_ENV: $FLASK_ENV
  FLASK_APP: $FLASK_APP
  APP_NAME: $APP_NAME
  APP_URL: $APP_URL
  PORT: $PORT

services:
  jada-server:
    entrypoint: ['./scripts/deps.sh', './scripts/start.sh']
    image: astongemmy/jada-server:latest
    container_name: jada-server
    working_dir: /app
    build: .
    volumes:
      - ./.venv:/app/.venv/
      - .:/app
    ports:
      - "$PORT:$PORT"
    # expose:
      - $PORT
    depends_on:
      - redis
    environment:
      <<: *shared-variables
    networks:
      - jada-network
  
  redis:
    image: redis:latest
    networks:
      - jada-network

networks:
  jada-network:
    name: jada-network