x-environment: &shared-variables
  PYTHONDONTWRITEBYTECODE: $PYTHONDONTWRITEBYTECODE
  CORS_ORIGIN: $CORS_ORIGIN
  FLASK_ENV: $FLASK_ENV
  FLASK_APP: $FLASK_APP
  APP_NAME: $APP_NAME
  APP_URL: $APP_URL

services:
  jada-server:
    entrypoint: ["gunicorn", "--bind", ":8080", "--workers", "1", "--threads", "8", "--timeout", "120", "main:app"]
    # entrypoint: ['./scripts/deps.sh', './scripts/start.sh']
    # image: astongemmy/jada:latest
    working_dir: /app
    build: .
    volumes:
      - ./.venv:/app/.venv/
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      <<: *shared-variables
  
  redis:
    image: redis:latest