name: Production - CI/CD

on:
  push:
    branches:
      - main
    tags:
      - deploy-production-v**

jobs:
  build_and_push:
    # if: startsWith(github.ref, 'refs/tags/deploy-production-v')
    environment: production
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Create .env File
      run: |
        echo "PYTHONDONTWRITEBYTECODE=${{ secrets.PYTHONDONTWRITEBYTECODE }}" >> .env
        echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> .env
        echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
        echo "CORS_ORIGIN=${{ secrets.CORS_ORIGIN }}" >> .env
        echo "FLASK_APP=${{ secrets.FLASK_APP }}" >> .env
        echo "APP_NAME=${{ secrets.APP_NAME }}" >> .env
        echo "APP_URL=${{ secrets.APP_URL }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "FLASK_ENV=production" >> .env

    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        # tags: ${{ secrets.DOCKER_USERNAME }}/jada:latest
        run: './scripts/docker/build.sh'
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Image to Docker Hub
      run: './scripts/docker/push.sh'